Table User {
  id int [pk]
  email varchar
}

Table Order {
  id int [pk]
  user_id int [ref: > User.id]
  status varchar
}

Table Product {
  id int [pk]
  price decimal
}

Table OrderItem {
  order_id int [ref: > Order.id]
  product_id int [ref: > Product.id]
  quantity int
}